name: Testing decryption

on:
  push:
    branches: [ 'main']
    tags: [ 'v*' ]
  pull_request:
    branches: [ 'main']
  #schedule:
  #  - cron: '15 8 * * 3' # Run weekly

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test decryption of zip
      shell: bash
      run: |
        set -x
        gpg --quiet --batch --yes --decrypt --passphrase="$REFPROP_GPG_PASSPHRASE" --output REFPROP.zip REFPROP.zip.gpg
        unzip REFPROP.zip -d REFPROP 
        ls REFPROP
      env:
          REFPROP_GPG_PASSPHRASE: ${{ secrets.REFPROP_GPG_PASSPHRASE }}
          
    - name: Test building of REFPROP shared library
      shell: bash
      run: |
        chmod +x decrypt.sh 
        ./decrypt.sh 
        
      env:
          REFPROP_GPG_PASSPHRASE: ${{ secrets.REFPROP_GPG_PASSPHRASE }}
        